### ISSUE TITLE
how to use scale_factor in hic_matrix?

### ISSUE THREAD

**Issue by Linhua-Sun** [deeptools/pyGenomeTracks#153]
pyGenomeTracks 3.2
python 3.6.9

Hi:
    Thanks for this wonderful tool. I have used it for a while. There is a option ( `scale_factor`) that I can't understand how to use. 
`scale_factor`:  "optional if the values in the matrix need to be scaled the following parameter can be used. This is useful to plot multiple hic-matrices on the same scale scale factor = 1"
I tried to add it with hic matrix，but it doesn't change the output. The figure legend max value are still different.

```
[Control_001K_SmKr]
file=Control_001K_SmKr.h5
title = Ctrl
depth = 50000
height = 6
transform = log1p
show_masked_bins = false
file_type = hic_matrix
colormap=gnuplot2
scale_factor = 1

[S2_001K_SmKr]
file=S2_001K_SmKr.h5
title = Heat
depth = 50000
height = 6
transform = log1p
show_masked_bins = false
file_type = hic_matrix
colormap=gnuplot2
scale_factor = 1
```

**Comment by lldelisle** [comment]
Hi,
`scale_factor` is the value by which you would like to multiply the values of your matrix. By default it is set to 1. So putting it to 1 does not change anything. However, putting it to something else like 12 does:
```ini

[hic matrix]
file = Li_et_al_2015.h5
title = depth = 200000; transform = log1p; min_value = 5
depth = 200000
min_value = 5
max_value = 1000
transform = log1p
file_type = hic_matrix
show_masked_bins = false

[hic matrix 2]
file = Li_et_al_2015.h5
title = same but orientation=inverted; and scale_factor = 12
depth = 200000
min_value = 5
max_value = 1000
transform = log1p
file_type = hic_matrix
show_masked_bins = false
scale_factor = 12
orientation = inverted

[x-axis]
```
`pgt --tracks browser_tracks_hic_rasterize_height.ini --region X:2500000-2600000 --trackLabelFraction 0.23 --width 38 -o master_plot_hic_rasterize_height.png`
![master_plot_hic_rasterize_height](https://user-images.githubusercontent.com/30404086/70603413-cc32af80-1bf6-11ea-855d-1c3e00793ef0.png)

**Comment by yichao-cai** [comment]
Sorry to reopen this discussion. I am also looking at the `scale_factor` parameter. Could really use some help on this.

What I am trying to do is to get a consistent color scale bar across multiple Hi-C matrix tracks.
For example, I have two matrix:
1. Matrix A: matrix value range (0,100), color bar range (0,100)
2. Matrix B: matrix value range (0,50), color bar range(0, 50)
Aim: I want to make the two matrixes have the same color scale at (0,100)

My attempts: I supplied `scale_factor =2` to Matrix B. Although I can get a color bar with range (0,100) for Matrix B, the values in it were all different from the original one (2 times).

How can I retain the original values in the matrix while getting a consistent color scale bar? Or, in another way, how can I explicitly map values to a range of colors?

**Comment by joachimwolff** [comment]
Hi,

first of all: Do you have the most recent version of pyGenomeTracks installed? It is version 3.6 (https://github.com/deeptools/pyGenomeTracks/releases/tag/3.6) from November 2020.

Best,

Joachim

**Comment by lldelisle** [comment]
Hi,
I am not sure I understand correctly. If you just want to have the same color bar for all hic you can use: `max_value = 100` in both, this will keep the good values in your matrix and just change the color corresponding to 50 in the matrix B.
If there is a difference between matrix A and matrix B for example not the same number of pairs or something like this, then you want to use the `scale_factor` which is to multiply each value of the matrix by this scale_factor.
Tell me if it answered your question.

**Comment by yichao-cai** [comment]
@joachimwolff Thanks for the kind reminder to check the version. I am using version 3.2. The reason why I am a bit reluctant to update is that I have a customed track class based on version 3.2. And I think on a newer version pygenometrack changed some setting and structure of the general track class. If I upgrade to the newest version, I might need to re-write the whole customed track again.

@lldelisle Thank you so much for the suggestion. I tried setting `max_value` and it worked! It seems that the color range would be automatically mapped to the max and min values in the matrix (without setting `min_value` and `max_value`). But if the `min_value` and `max_value` are set explicitly, the color range would be mapped to them.

![image](https://user-images.githubusercontent.com/24425664/105482704-b8a3b480-5ce3-11eb-97f9-e2345f4903ff.png)


The question I had previously is that the color palette is fixed and dynamically mapped to the min and max value, which would result in the following mapping:
 
(`min_value` and `max_value` not set)
Matrix A value and color mapping:
0  -------------------- 100
blue -----------------  red
Matrix B value and color mapping:
0  -------------------- 50
blue -----------------  red

If you look at the same color red, they represent different intensities in two matrixes. And I want to standardize this so that the same red color would represent 100 in both matrixes.

Thanks again for the prompt reply!

**Comment by lldelisle** [comment]
Hi,
Happy that it solved your issue.
Indeed 3.2, you are using a old version... I think you should be able to update your custom track without much difficulties... You just need to add some dictionaries at the beginning with default values and possible values (see https://pygenometracks.readthedocs.io/en/latest/content/adding-new-tracks.html). If you update it and you think your custom track can be helpful for other user, do not hesitate to do a pull request...
