### ISSUE TITLE
Unexpected behavior of colormap in BED tracks

### ISSUE THREAD

**Issue by Zepeng-Mu** [deeptools/pyGenomeTracks#244]
- [x] Paste your pyGenomeTracks version (`pyGenomeTracks --version`) and your python
  version (`python --version`) below.
Python 3.7.0 PyGenomeTracks 3.4
  - [x] Paste the full pyGenomeTracks command that produces the issue below
  (ignore if you simply spotted the issue in the code/documentation).
```
[ATAC_Mono_S]
file = Monocytes-S_peaks.bed
title = ATAC-seq Monocytes-S
labels = false
height = 0.1
color = RdBu
border_color = white
file_type = bed

[spacer]
height = 0.03

[ATAC_Mono_U]
file = Monocytes-U_peaks.bed
title = ATAC-seq Monocytes-U
labels = false
height = 0.1
color = RdBu
border_color = none
file_type = bed
```
  - [x] Paste the output printed on screen from the command that produces the issue
  below (ignore if you simply spotted the issue in the code/documentation).
[![Screen-Shot-2020-06-04-at-11-05-17.png](https://i.postimg.cc/k4yBj05L/Screen-Shot-2020-06-04-at-11-05-17.png)](https://postimg.cc/zbVzvPKk)

Hi, I am trying to change the color of bed tracks using "Score" field from a BED6 file which is simply the first 6 columns of "narrowpeak" output from MACS2. But the colormap is not shown properly and when I set border_color to white nothing is shown.

Thanks!!

**Comment by lldelisle** [comment]
Hi,
Thanks for the detail issue.
First, the colormap does not show because the track height is too small. You need to increase it if you want to see it.
Then, the output of macs2 may provide multiple times the same peak because it detects multiple summit within the same peak. This is why you see three times the same interval on the right. If you want to see all peaks in one line, I suggest you to use `display = collapsed`. Because you put `height = 0.1` and each peak was only one third of the track when you put `border_color = white`, you don't see the peaks anymore because by default the width of the border is 0.5 so it fully covers your peaks. Do not hesitate to play with the parameter `line_width` to be able to see your peaks. Finally, your result may be disappointing because all peaks have the same color, this is due to the fact that some peaks in macs2 output have a very high score, so to see multiple colors on the same region you should play with `max_value`.
Please, tell me if you managed to have a figure which fit your expectations.

**Comment by Zepeng-Mu** [comment]
Hi, this advice is really helpful. Thanks!
