### ISSUE TITLE
Missing y-axis scale on pyGenomeTracks

### ISSUE THREAD

**Issue by benxiahu** [deeptools/pyGenomeTracks#280]
Hello,
   when I used pyGenomeTracks to make a heatmap for Hi-C contact matrix, the y-axis scale is missing.
   FYI, matplotlib-3.1.3

![image](https://user-images.githubusercontent.com/12387462/93100044-b7e47d00-f676-11ea-9534-94e50d4b4866.png)

Do you know how to solve this issue?
Best

**Comment by lldelisle** [comment]
Hi,
Which version of pyGenomeTracks are you using?

**Comment by lldelisle** [comment]
I think this problem was solved in version 3.1. If you are using an older version, please upgrade pyGenomeTracks.

You may have some warnings as in version 3.2 we changed the keywords in the configuration file (https://pygenometracks.readthedocs.io/en/latest/content/releases.html). However, for the moment, it will still work with the old configuration file.

**Comment by benxiahu** [comment]
hi,
   Thanks for your reply.
   I directly installed pyGenomeTracks using conda: https://anaconda.org/bioconda/pygenometracks

**Comment by lldelisle** [comment]
Can you do `pyGenomeTracks --version`, please?

**Comment by lldelisle** [comment]
We recently noticed that the version of pyGenomeTracks installed by conda is linked to your python version. It is possible that if you did not specify the version of pyGenomeTracks, it installed 2.1.
To update it, you can do `conda install pygenometracks=3.5`.

**Comment by lldelisle** [comment]
If the issue is not solved, feel free to reopen it.
