### ISSUE TITLE
[Galaxy wrappers] Legend placement not correct

### ISSUE THREAD

**Issue by joachimwolff** [deeptools/pyGenomeTracks#35]
Independent of selecting the option `Top` or `Bottom` the legend is placed at the top.

**Comment by joachimwolff** [comment]
It looks like it depends not on 'bottom' or 'top' where the label is placed but where the track `[x-axis]` is placed in the tracks.ini file. I fixed this for the Galaxy wrapper by placing the `[x-axis]` track at the top or at the bottom of the file. 

I think we have to come up with a better solution, or is it meant to be this way? Than the naming `top` and `bottom` is misleading.

**Comment by fidelram** [comment]
I thought that you could specify where to put the xticklabels on the x-axis, either on top of the line or at the bottom. I am surprised that it does not work properly.

Can you show an example?

**Comment by lldelisle** [comment]
Hi,
I think @joachimwolff  is right, the where option is misleading as it could mean:

- where you want to put the x-axis
- where you want to put the labels of the x-axis

As all other tracks, xaxis is plot at its position in the config file, you can have multiple x-axis. For example,
```
[x-axis]
where = top
title = where=top
[test bigwig lines]
file = bigwig2_X_2.5e6_3.5e6.bw
color = gray
height = 2
title = a bigwig
show data range = yes
max_value = 50

[x-axis]

[x-axis]
where = top
title = where=top

[test bigwig lines]
file = bigwig2_X_2.5e6_3.5e6.bw
color = gray
height = 2
title = a bigwig
show data range = yes
max_value = 50

[x-axis]
```
with `pgt --tracks tracks.ini --region X:2700000-3100000 -o test.png` would give:
![test](https://user-images.githubusercontent.com/30404086/65606150-a3f9c400-dfaa-11e9-821b-cc5075ac2574.png)

I propose to change the help for x-axis:
Instead of:
https://github.com/deeptools/pyGenomeTracks/blob/1352c2a16ab4ada31bcf8fa06d34df3a83422dad/pygenometracks/makeTracksFile.py#L42-L46
We could put:
```
# This block describes the x-axis, put it where you want your x-axis to appear
[x-axis]
#optional
#fontsize=20
# default is bottom meaning that the labels will be below the axis line
# where=top
```

What do you think?
