### ISSUE TITLE
cannot plot track of bed12 genes with intron 

### ISSUE THREAD

**Issue by brainfo** [deeptools/pyGenomeTracks#99]
I'm using pyGenomeTracks to plot genes, and get this output:
![image](https://user-images.githubusercontent.com/11832080/65407801-39b01a80-de16-11e9-8287-2c35faed5266.png)
the upper track is from bed12 file:
![image](https://user-images.githubusercontent.com/11832080/65407850-6401d800-de16-11e9-9838-f17674c4fada.png)
**could the 9th column (for color) be all zeros?**
with this ini:
```py
[gene]
file = gencode_vM22_ucsc.bed12
height = 3
title = genes
fontsize = 10
gene rows = 3
type = genes
style = UCSC
file_type = bed
```
the lower track is from bed6 file.

from your BedTrack.py:
```py          
     if self.bed_type == 'bed12':
                if self.properties['style'] == 'flybase':
                    self.draw_gene_with_introns_flybase_style(ax, bed, ypos,
                                                              rgb, edgecolor,
                                                              linewidth)
                else:
                    self.draw_gene_with_introns(ax, bed, ypos, rgb, edgecolor,
                                                linewidth)
    else:
                self.draw_gene_simple(ax, bed, ypos, rgb, edgecolor, linewidth)
```

it's weird that my bed12 file cannot be drawn, and any style, flybase, UCSC, and non gives the same slim black non-directional straight lines.

I'm using pyGenomeTrack 3.0 and python 3.6.7,
I cannot see how your readBed.py scripts can get the format of my bed12 file wrong.

I'd really appreciate your help.

Thanks!

**Comment by bgruening** [comment]
@brainfo can you please try the latest version and report back if this still is an issue?

**Comment by brainfo** [comment]
> @brainfo can you please try the latest version and report back if this still is an issue?

for version 3.1, problem remains, 3.1.1 the same.

**Comment by brainfo** [comment]
I inserted some print command, and used pyGenomeTracks to plot this bed12 file,  and found it can well run to the plot vertices and small arrows using the character '<' or '>' over the back bone part and get right coordinates (the "draw_gene_with_introns" function). 
But it can only plot black back bone of my bed12 genes.

Then I checked matplotlib to draw arrows and vertices, and find it worked normally, and assured using the same python.

![image](https://user-images.githubusercontent.com/11832080/65427189-5d8a5500-de44-11e9-8810-6aa50aba732d.png)

So I still haven't pin on the problem.

**Comment by lldelisle** [comment]
Hi,
The format you used is not a bed12 format:
https://genome.ucsc.edu/FAQ/FAQformat.html#format1
The 11th column of a bed12 format is the block length and the 12th is the block starts.
Here, it looks like the file you are using put in column 11 the starts and in column 12 the ends...
Where did you get the file? Do you know how to change it?

**Comment by anthony-aylward** [comment]
I think I am having the same issue. See my example data [here](https://github.com/anthony-aylward/pygenometracks-issue).

## Expected behavior

When provided with a genes file in BED12 format, [pyGenomeTracks](https://github.com/deeptools/pyGenomeTracks) should plot a gene track with thick exons and thin introns.

## Observed behavior

With a BED12 input file, pyGenomeTracks plots only the thin "backbone" of each gene in the gene track.

## Reproducible example

A fairly minimal example of the [issue](https://github.com/deeptools/pyGenomeTracks/issues/99) follows:

To reproduce the issue:
```sh
git clone https://github.com/anthony-aylward/pygenometracks-issue.git
cd pygenometracks-issue
sh test.sh
```

This will write a SVG file to `test.svg`:
![test svg](https://github.com/anthony-aylward/pygenometracks-issue/blob/master/test.svg)

I have experienced the same issue when using pyGenomeTracks version 2.1 and 3.1.1, and using python version 3.6.6 or 3.7.1.

Contents of `test.sh`:
```sh
pyGenomeTracks \
  --tracks tracks.ini \
  --region chr11:113733128-114324674 \
  --outFileName test.svg
```

Contents of `tracks.ini`
```
[gene]
file = hg19-bed12-chr11.bed.gz
height = 3
title = genes
fontsize = 10
gene rows = 3
type = genes
style = UCSC
file_type = bed

[gene]
file = hg19-chr11.bed.gz
height = 3
title = genes
fontsize = 10
gene rows = 3
type = genes
style = UCSC
file_type = bed
```

**Comment by lldelisle** [comment]
Hi,
Here again it is because the bed12 format is not the one described in UCSC:12th column of bed12 expect the starts position as relative to the column2 not absolute.
You can convert it to the correct bed12 format with awk:
`zcat hg19-bed12-chr11.bed.gz | awk -v OFS="\t" '{start = $2; split($12, a, ","); $12=""; printf($0); for(i in a){if(a[i]!=""){printf("%d,",a[i]-start)}}; printf("\n")}' `
Where did you get the file?
Maybe we could put an additional parameter to specify which type of bed12 it is... What do you think?

**Comment by brainfo** [comment]
> Hi,
> The format you used is not a bed12 format:
> https://genome.ucsc.edu/FAQ/FAQformat.html#format1
> The 11th column of a bed12 format is the block length and the 12th is the block starts.
> Here, it looks like the file you are using put in column 11 the starts and in column 12 the ends...
> Where did you get the file? Do you know how to change it?

See. Thank you very much!

**Comment by lldelisle** [comment]
Hi,
In the next version, we will check that the bed12 is well formatted and will raise an error if it is not.
Thanks for reporting this issue, this help to improve the tool.

**Comment by lldelisle** [comment]
@anthony-aylward 
With the next version, you would have:
```bash
AssertionError: The block number 0 of line 2 has a starting position greater than the end of the feature:
chr11   127133  131853  LINC01001       0       -       131853  131853  0,0,0   3       4240,58,102,    127133,131466,131751,
The 12th field of a bed12 should contains relative start positions of blocks.
```
Here is what I did:
```bash
mv hg19-bed12-chr11.bed.gz hg19-bed12-chr11_ori.bed.gz
zcat hg19-bed12-chr11_ori.bed.gz | awk -v OFS="\t" '{start = $2; split($12, a, ","); $12=""; printf($0); for(i in a){if(a[i]!=""){printf("%d,",a[i]-start)}}; printf("\n")}' | gzip > hg19-bed12-chr11.bed.gz
pyGenomeTracks   --tracks tracks.ini   --region chr11:113733128-114324674   --outFileName test.png
```
And I think it worked:
![test](https://user-images.githubusercontent.com/30404086/65587560-58352380-df86-11e9-86d3-1f84851440bf.png)

Thanks for reporting this issue and creating a repo for that, this is very helpful.

**Comment by anthony-aylward** [comment]
Thanks @lldelisle , your solution resolves the issue for me. I originally pulled my data from UCSC's [refFlat](https://genome.ucsc.edu/goldenpath/gbdDescriptions.html) (because that was the source used by [LocusZoom](http://locuszoom.org)), but that source is now deprecated.

I don't think there's a need to consider alternate versions of the BED12 format, but I think a lot of researchers will probably find it helpful if you reference or include among your examples a preferred set of human gene coordinates from GRCh37 and/or GRCh38 .
